### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by jeffwidman** [smurfix/flask-script#186]
Flask now ships the `run` command and a relatively flexible built-in CLI interface: https://flask.palletsprojects.com/en/1.1.x/cli/

@smurfix can you archive this repo? That would indicate to folks they should use that instead.

**Comment by smurfix** [comment]
I pushed a delete-all change to the new "removed" branch and set that as the default.

**Comment by jeffwidman** [comment]
Actually, what I meant was this: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-repositories

You can mark a repo as "Archived"/"Read-only" in Github. 

That would let you keep the `master` branch as default so that folks can still see what the code looks like, while still clearly indicating the repo is no longer being maintained.

What do you think?
